---
title: "Rebecca N Final Project"
output: html_notebook
author: "Rebecca Neal"
date: " 29 April 2020"
version: "version 1.0"
---

This is for the final exam project in EDRM 718.

### First we will load the package
```{r include=FALSE}
library(tidyverse)

```

### Load the JP Demographics File
```{r}
JP_Demo <- read_csv("Job Prep Demographics.csv", skip = 6,
                    col_names = c("ID", "School", "Age", "Gender", "Discipline"),
                    JP_Demo$ID <- parse_integer(JP_Demo$ID))
                    
```

### Tidy and rename JP_Demo to Demographics File
```{r}
Demographics <- JP_Demo %>%
  fill("Discipline") %>%
  filter(ID >0)

```

### Double check that no ID numbers are repeated
```{r}
check_Demographics <- Demographics %>%
  count(ID) %>%
  filter(n >1)

```
#### Based on this check, we are certain that no ID numbers are repeated

### Load Job Prep Data
```{r}
JP_Data <- read_csv("Job Prep GPA Data.csv", skip = 5,
                    col_names = c("ID", "School", "Age", "Gender", "S1_Credits", "S1_GPA",
                                  "S2_Credits", "S2_GPA"),col_types = cols(S1_GPA = col_double()))
                    
```


### Identify 10% largest residual
```{r}
Top_10 <- JP_Data %>%
  mutate(GPA_Residual = ((S2_GPA - S1_GPA)^2)^(1/2)) %>%
  arrange(desc(GPA_Residual)) %>%
  mutate(Top_10_Residual = cut(GPA_Residual,
                              breaks = c(0,.70,1.36),
                             labels = c("Cool to Use", "Top 10% Residual"))) %>%
  mutate()
Top_10

```


### Chart showing difference 10% Highest Residuals
```{r}
GPA_Issue_Plot <- Top_10 %>%
  ggplot(aes(x = ID, y = GPA_Residual, color = Top_10_Residual)) +
  geom_point()+
  labs(x = "Student ID Number",
       y = "Difference Between GPA First Semester and Second Semester",
       title = "Top 10% Highest Differences in GPA", 
       subtitle = "Residual Difference in GPA")
  GPA_Issue_Plot

```





